# Generated by Django 5.1.6 on 2025-02-12 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defense'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('photo', models.ImageField(blank=True, default='photos/default.png', upload_to='shields')),
                ('slug', models.SlugField(unique=True)),
                ('birth_date', models.DateTimeField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.team')),
            ],
        ),
    ]
