# Generated by Django 5.1.6 on 2025-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='players/photos/default.png', upload_to='photos'),
        ),
    ]
