# Generated by Django 5.1.6 on 2025-02-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_photo'),
        ('teams', '0003_alter_team_name_alter_team_shield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('birth_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('photo', models.ImageField(blank=True, default='players/photos/default.png', upload_to='players/photos')),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
