# Generated by Django 5.1.6 on 2025-02-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_team_delete_player'),
        ('teams', '0003_alter_team_name_alter_team_shield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Player',
        ),
    ]
