# Generated by Django 5.1.6 on 2025-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='team',
            name='shield',
            field=models.ImageField(blank=True, default='teams/shields/default.png', upload_to='shields'),
        ),
    ]
